### PR TITLE
Add Docker Compose Setup for Lazy Indexer and Opencast

### PR DESCRIPTION
**Pull request by gabrieltemtsen**
The PR adds a docker-compose.yml configuration to simplify the process of setting up and running both the Lazy Indexer and Opencast services in Docker containers:

- Added a docker-compose.yml file to set up and run the Lazy Indexer and Opencast using Docker.
- Created a Docker image for the Lazy Indexer and published it to Docker Hub as 'gabrieltemtsen/lazy-indexer:latest'.
- Configured the services to use PostgreSQL and Redis with the appropriate environment settings(from the env samples).

### CODE REVIEW

**Comment by stephancill** [comment]
Hey @gabrieltemtsen thank you for this!

I tried running on my machine and it seems like the node alpine image used in the dockerfile is missing a python installation

```
$ docker-compose up
...
[+] Building 167.0s (8/10)                                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                                      0.0s
 => => transferring dockerfile: 475B                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/node:18-alpine                                                                                         4.2s
 => [1/6] FROM docker.io/library/node:18-alpine@sha256:17514b20acef0e79691285e7a59f3ae561f7a1702a9adc72a515aef23f326729                                   4.4s
 => => resolve docker.io/library/node:18-alpine@sha256:17514b20acef0e79691285e7a59f3ae561f7a1702a9adc72a515aef23f326729                                   0.0s
 => => sha256:98d10a402a711e0f973defbe2811235c6c8063234155c82b87e2a43c66771026 1.38MB / 1.38MB                                                            0.4s
 => => sha256:18af9f4a60fa210999a9ddd6def4a9c43fac937d6fb07066c570102ebd1f200a 443B / 443B                                                                0.3s
 => => sha256:17514b20acef0e79691285e7a59f3ae561f7a1702a9adc72a515aef23f326729 7.67kB / 7.67kB                                                            0.0s
 => => sha256:603c6873f8dfbbc0bce4e042102fce439641601b69656dca994d74777c1ec53c 1.72kB / 1.72kB                                                            0.0s
 => => sha256:b0c5385c383cf88d465e1e7392b5840adb2d705d1754791ab1d568d9fe3c62db 6.36kB / 6.36kB                                                            0.0s
 => => sha256:dd6d84f5b2bf2f1bffc5b49d9faa5a7b7e432a8797239f465e3d1cc3ddd7e764 39.54MB / 39.54MB                                                          2.6s
 => => extracting sha256:dd6d84f5b2bf2f1bffc5b49d9faa5a7b7e432a8797239f465e3d1cc3ddd7e764                                                                 1.0s
 => => extracting sha256:98d10a402a711e0f973defbe2811235c6c8063234155c82b87e2a43c66771026                                                                 0.1s
 => => extracting sha256:18af9f4a60fa210999a9ddd6def4a9c43fac937d6fb07066c570102ebd1f200a                                                                 0.0s
 => [internal] load build context                                                                                                                         0.3s
 => => transferring context: 5.89MB                                                                                                                       0.1s
 => [2/6] WORKDIR /app                                                                                                                                    0.0s
 => [3/6] COPY package*.json ./                                                                                                                           0.0s
 => ERROR [4/6] RUN yarn install                                                                                                                        158.1s
------
 > [4/6] RUN yarn install:
#0 0.759 yarn install v1.22.19
#0 0.797 info No lockfile found.
#0 0.832 [1/5] Validating package.json...
#0 0.832 [2/5] Resolving packages...
#0 44.35 warning patch-package > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
#0 44.48 warning patch-package > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
#0 44.66 warning patch-package > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
#0 48.39 warning react-query > broadcast-channel > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
#0 48.39 warning react-query > broadcast-channel > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
#0 60.26 warning wagmi > @wagmi/connectors > @walletconnect/modal > @walletconnect/modal-ui > motion > @motionone/vue@10.16.4: Motion One for Vue is deprecated. Use Oku Motion instead https://oku-ui.com/motion
#0 74.48 warning eslint > @humanwhocodes/config-array@0.10.7: Use @eslint/config-array instead
#0 74.80 warning eslint > file-entry-cache > flat-cache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
#0 74.82 warning eslint > @humanwhocodes/config-array > @humanwhocodes/object-schema@1.2.1: Use @eslint/object-schema instead
#0 75.16 warning eslint-config-next > eslint-import-resolver-typescript > glob@7.2.3: Glob versions prior to v9 are no longer supported
#0 75.38 warning eslint-config-next > @next/eslint-plugin-next > glob@7.1.7: Glob versions prior to v9 are no longer supported
#0 75.38 warning eslint-config-next > @next/eslint-plugin-next > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
#0 76.34 warning jest > jest-cli > jest-config > glob@7.2.3: Glob versions prior to v9 are no longer supported
#0 76.45 warning jest > @jest/core > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
#0 76.68 warning jest > jest-cli > jest-config > jest-circus > jest-runtime > glob@7.2.3: Glob versions prior to v9 are no longer supported
#0 76.85 warning jest > @jest/core > @jest/reporters > glob@7.2.3: Glob versions prior to v9 are no longer supported
#0 77.01 warning jest > jest-cli > jest-config > babel-jest > babel-plugin-istanbul > test-exclude > glob@7.2.3: Glob versions prior to v9 are no longer supported
#0 78.13 warning jest-environment-jsdom > jsdom > abab@2.0.6: Use your platform's native atob() and btoa() methods instead
#0 78.13 warning jest-environment-jsdom > jsdom > data-urls > abab@2.0.6: Use your platform's native atob() and btoa() methods instead
#0 78.20 warning jest-environment-jsdom > jsdom > w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
#0 78.22 warning jest-environment-jsdom > jsdom > domexception@4.0.0: Use your platform's native DOMException instead
#0 84.18 [3/5] Fetching packages...
#0 133.0 [4/5] Linking dependencies...
#0 133.0 warning "@farcaster/hub-web > @improbable-eng/grpc-web@0.15.0" has unmet peer dependency "google-protobuf@^3.14.0".
#0 133.0 warning " > @frames.js/render@0.2.23" has incorrect peer dependency "@types/react@^18.2.0".
#0 133.0 warning " > @frames.js/render@0.2.23" has unmet peer dependency "@types/react-native@^0.73.0".
#0 133.0 warning " > @frames.js/render@0.2.23" has unmet peer dependency "react-native@^0.74.3".
#0 133.0 warning "@frames.js/render > frames.js@0.18.2" has unmet peer dependency "@cloudflare/workers-types@^4.20240320.1".
#0 133.0 warning "@frames.js/render > frames.js@0.18.2" has unmet peer dependency "@lens-protocol/client@^2.0.0".
#0 133.0 warning "@frames.js/render > frames.js@0.18.2" has unmet peer dependency "@types/express@^4.17.21".
#0 133.0 warning "@frames.js/render > frames.js@0.18.2" has unmet peer dependency "@xmtp/frames-validator@^0.6.2".
#0 133.1 warning " > frames.js@0.17.5" has unmet peer dependency "@cloudflare/workers-types@^4.20240320.1".
#0 133.1 warning " > frames.js@0.17.5" has unmet peer dependency "@lens-protocol/client@^2.0.0".
#0 133.1 warning " > frames.js@0.17.5" has unmet peer dependency "@types/express@^4.17.21".
#0 133.1 warning " > frames.js@0.17.5" has unmet peer dependency "@xmtp/frames-validator@^0.6.2".
#0 133.1 warning "react-hot-toast > goober@2.1.14" has unmet peer dependency "csstype@^3.0.10".
#0 133.1 warning "wagmi > @wagmi/connectors > @metamask/sdk > react-native-webview@11.26.1" has unmet peer dependency "react-native@*".
#0 133.1 warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
#0 154.1 [5/5] Building fresh packages...
#0 154.7 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#0 154.7 error /app/node_modules/ref-napi: Command failed.
#0 154.7 Exit code: 1
#0 154.7 Command: node-gyp-build
#0 154.7 Arguments: 
#0 154.7 Directory: /app/node_modules/ref-napi
#0 154.7 Output:
#0 154.7 gyp info it worked if it ends with ok
#0 154.7 gyp info using node-gyp@10.1.0
#0 154.7 gyp info using node@18.20.4 | linux | arm64
#0 154.7 gyp ERR! find Python 
#0 154.7 gyp ERR! find Python Python is not set from command line or npm configuration
#0 154.7 gyp ERR! find Python Python is not set from environment variable PYTHON
#0 154.7 gyp ERR! find Python checking if "python3" can be used
#0 154.7 gyp ERR! find Python - executable path is ""
#0 154.7 gyp ERR! find Python - "" could not be run
#0 154.7 gyp ERR! find Python checking if "python" can be used
#0 154.7 gyp ERR! find Python - executable path is ""
#0 154.7 gyp ERR! find Python - "" could not be run
#0 154.7 gyp ERR! find Python 
#0 154.7 gyp ERR! find Python **********************************************************
#0 154.7 gyp ERR! find Python You need to install the latest version of Python.
#0 154.7 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#0 154.7 gyp ERR! find Python you can try one of the following options:
#0 154.7 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#0 154.7 gyp ERR! find Python (accepted by both node-gyp and npm)
#0 154.7 gyp ERR! find Python - Set the environment variable PYTHON
#0 154.7 gyp ERR! find Python - Set the npm configuration variable python:
#0 154.7 gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
#0 154.7 gyp ERR! find Python For more information consult the documentation at:
#0 154.7 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#0 154.7 gyp ERR! find Python **********************************************************
#0 154.7 gyp ERR! find Python 
#0 154.7 gyp ERR! configure error 
#0 154.7 gyp ERR! stack Error: Could not find any Python installation to use
#0 154.7 gyp ERR! stack at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:306:11)
#0 154.7 gyp ERR! stack at PythonFinder.findPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:164:17)
#0 154.7 gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#0 154.7 gyp ERR! stack at async configure (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:27:18)
#0 154.7 gyp ERR! stack at async run (/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
#0 154.7 gyp ERR! System Linux 5.15.49-linuxkit
#0 154.7 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#0 154.7 gyp ERR! cwd /app/node_modules/ref-napi
#0 154.7 gyp ERR! node -v v18.20.4
#0 154.7 gyp ERR! node-gyp -v v10.1.0
#0 154.7 gyp ERR! not ok
------
failed to solve: process "/bin/sh -c yarn install" did not complete successfully: exit code: 1
```

**Comment by stephancill** [comment]
@gabrieltemtsen reminder to update the Dockerfile here to include the python install commands

**Comment by gabrieltemtsen** [comment]
updated the install command

**Comment by stephancill** [comment]
@gabrieltemtsen I made the following changes to get it to run on my computer. However it still needs to run the migrations for the lazy indexer. Perhaps you can update the lazy indexer startup script to run the migrations in typescript directly on startup as opposed to running a separate script.

If you give me write access to your fork i can commit this directly if you'd like.

```patch
diff --git a/.env.sample b/.env.sample
index 2da3a88..31556df 100644
--- a/.env.sample
+++ b/.env.sample
@@ -3,9 +3,9 @@ DATABASE_URL="postgres://replicator:password@localhost:6541/replicator?schema=pu
 
 ## Farcaster Hub (optional: only required for writing)
 # The format is <host>:<port>, do not include the protocol
-FC_HUB_URL="localhost:2283"
+FC_HUB_URL="hub-grpc.pinata.cloud"
 # If using the hub monorepo this should be set to false unless you setup TLS
-FC_HUB_USE_TLS="false"
+FC_HUB_USE_TLS="true"
 
 ## App signer (required for registering new app signer keys)
 # Use your personal mnemonic for running locally
diff --git a/Dockerfile b/Dockerfile
index a2bf5cb..63e7f2e 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,23 +1,26 @@
 # Use the official Node.js image.
-FROM node:18-alpine
+FROM node:20
+
+# Install necessary build tools
+RUN apk add python3 make g++ gcc
 
 # Set the working directory inside the container.
 WORKDIR /app
 
 # Copy the package.json and yarn.lock files.
-COPY package*.json ./
+COPY package.json yarn.lock* ./
 
 # Install dependencies.
-RUN yarn install
-
-RUN apk add --no-cache python3 make g++ gcc
-
+RUN yarn install --frozen-lockfile
 
 # Copy the rest of the application code.
 COPY . .
 
+# Generate Prisma client
+RUN yarn prisma generate
+
 # Build the Next.js application.
-RUN yarn build
+RUN yarn build --no-lint
 
 # Expose the port the app runs on.
 EXPOSE 3000
diff --git a/docker-compose.yml b/docker-compose.yml
index c053e40..efa0015 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -32,7 +32,7 @@ services:
 
   # Lazy Indexer service
   lazy-indexer:
-    image: gabrieltemtsen/lazy-indexer # Update to point to the Lazy Indexer  image
+    image: stephancill/lazy-indexer
     container_name: lazy-indexer
     environment:
       DATABASE_URL: postgresql://indexer:password@postgres:5432/indexer
@@ -54,12 +54,15 @@ services:
   opencast:
     build: ./ # Update to point to the Opencast path
     container_name: opencast
+    env_file:
+      # Set in .env
+      # APP_FID
+      # APP_MNENOMIC
+      - .env
     environment:
       DATABASE_URL: postgresql://indexer:password@postgres:5432/indexer
-      FC_HUB_URL: localhost:2283
-      FC_HUB_USE_TLS: "false"
-      APP_FID: 1
-      APP_MNENOMIC: ""
+      FC_HUB_URL: "hub-grpc.pinata.cloud"
+      FC_HUB_USE_TLS: "true"
       NEXT_PUBLIC_FC_CLIENT_NAME: "Opencast"
       NEXT_PUBLIC_WALLETCONNECT_ID: "0fcda49e9f4acad4b84401373fbc5a4f"
       NEXT_PUBLIC_URL: "http://localhost:3000"

```

**Review by stephancill — APPROVED** [review]

**Pull request merged**
